config/routes.rb
Rails.application.routes.draw do


  root              'sale_pages#home'
  get '/help'     , to: 'sale_pages#help'
  get '/contact'  , to: 'sale_pages#contact'
  get '/new'      , to: 'items#new'
  
  get    '/login'    , to: 'sessions#new'
  post   '/login'    , to: 'sessions#create'
  delete '/logout'   , to: 'sessions#destroy'

  resources :items do 
  	resources :comments
  end

  resources :users
  #post 'items/:item_id/comments', to: 'comments#create'
end

app/models/comment.rb
class Comment < ActiveRecord::Base


  # validates :user_name, presence: true
  # validates :content, presence: true, length: {in: 30..500}

  #validate :comment_count_limit, :on => :create
#
#  #def comment_count_limit
#  #  limit_value = 10
#  #  if self.item.comments(:reload).count >= limit_value 
#  #    errors.add(:base, "Exceed the limitation number of comments. Only #{limit_value} comments are allowed")
#  #  end
  #end

  def replies
    Comment.where({ source_id: self.id, source_type: 'Comment' })
  end
end

app/models/item.rb
class Item < ActiveRecord::Base
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  validates_with AttachmentSizeValidator, attributes: :image, less_than: 1.megabytes

  after_validation :clean_paperclip_errors

  def clean_paperclip_errors
    errors.delete(:image)
  end

  def comments
  	Comment.where({ source_id: self.id, source_type: 'Item' })
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def show
    item = Item.find(params[:item_id])
    

    respond_to do |format|
      format.html { }
      format.json { }
    end    

  end



  def create
    item = Item.find(params[:item_id])
    comment = Comment.new(comment_params)

    if comment.save
      respond_to do |format|
        format.html { }
        format.json { }
      end

      #UserMailer.notify_comment(item, comment).deliver
    else
      #flash[:error] = comment.errors.full_messages.join("\n")
      flash[:error] = comment.errors.full_messages
    end

    redirect_to item
  end

  def destroy
    item = Item.find(params[:item_id])
    comment = Comment.find(params[:id])
    comment.destroy
    respond_to do |format|
      format.html { redirect_to item, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:user_name, :content, :source_id, :source_type)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  
  def edit
    @item = Item.find(params[:id])
  end

  def new
  	@item = Item.new
  end

  def show
    @item     = Item.find(params[:id])
    #@comment  = @item.comments.build
    #@comment = Comment.find_by(:id => params[:comment_id])

    @replies = Comment.where ({source_type: "Comment"})    
    @comment_id = params[:comment_id]


    #comment_id = @comment.id
    # debugger
    #@reply    = @comment.replies.build
    respond_to do |format|
      format.html
      format.json
      #format.js { render :show, type: params[:type] }
      format.js
    end


  end

  def create
    @item = Item.new(item_params)
    if @item.save
      # Handle a successful save.
      redirect_to @item
    else
      render 'new'
    end
  end


  def update
    @item = Item.find(params[:id]) 
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def item_params
      params.require(:item).permit(:image, :name, :description)
    end

    def comment_params
      params.require(:comment).permit(:source_id, :source_type => 'Item')
    end
end

app/controllers/sale_pages_controller.rb
class SalePagesController < ApplicationController
  def home
  	@items = Item.all
  end

  def help
  end

  def contact
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by(user_name: params[:session][:user_name])
  	if user && user.authenticate(params[:session][:password])
  		log_in user
      redirect_to root_path

  	else
      flash.now[:danger] = 'Invalid username/password'  
  		render 'new'
  	end
  	#render 'new'
  end

  def destroy
    log_out
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Sale Page"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/item_comments_helper.rb
module ItemCommentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper

end

app/helpers/sale_pages_helper.rb
module SalePagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
  end
end

app/views/items/_form.html.erb
<%= render 'shared/item_error_message' %>
<%= form_for(@item) do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name, class: 'form-control' %>
			
	<%= f.label :description %>	
	<%= f.text_area :description, class: 'form-control'	 %>
	
	<%= f.label :'Item image (less than 1 MB)'%>
	<%= f.file_field :image, class: 'form-control' %>
	<%= f.submit yield(:button_text) , class: "btn btn-primary" %>
<% end %>

app/views/items/_form_comment.html.erb
<%= form_for Comment.new, url: item_comments_path(@item) do |f| %>
  <%= f.label :'Name' %>
  <%= f.text_field :user_name, class: 'form-control custom-form' %>
      
  <%= f.label :content %> 
  <%= f.text_area :content, class: 'form-control custom-form'  %>
  

  <% if local_assigns[:form_type] == "Comment" %>
  	<%= f.hidden_field :source_type, :value => 'Item' %>
  	<%= f.hidden_field :source_id, :value => @item.id %>

  <% elsif local_assigns[:form_type] == "Reply" %>
	  <%= f.hidden_field :source_type, :value => 'Comment' %>
  	<%= f.hidden_field :source_id, :value => @comment_id %>
  <% end %>
  <%= f.submit local_assigns[:form_type] , class: "btn btn-primary custom-btn" %>
<% end %>

app/views/items/_sub_form_comment.html.erb
<%= render 'form_comment', form_type: 'Comment' %>

app/views/items/_sub_form_reply.html.erb
<%= render 'form_comment', form_type: 'Reply' %>

app/views/items/edit.html.erb
<% provide(:title, 'Edit item') %>
<% provide(:button_text, 'Save changes') %>
<h1>Update your item</h1>

<div class="row">
  <div class="col-sm-5 col-md-6">
  	<%= render 'form' %>
  </div>
</div>

app/views/items/new.html.erb
<% provide(:title, 'New item') %>
<% provide(:button_text, 'Create new item') %>

<h1> Add your items </h1>
<div class="row">
  <div class="col-sm-5 col-md-6">
		<%= render 'form' %>
	</div>
</div>

app/views/items/show.html.erb
<% provide(:title, @item.name) %>


<h1> <%= @item.name %> </h1>

<h4 class="item_data">
<% if logged_in? %>
  <%= link_to image_tag('edit-icon.png', size: '20x20', alt: 'edit icon') +  'Edit', edit_item_path(@item) %>
<% end %>
</h4>

<p>
<%= link_to image_tag('facebook_icon.png', size: "50x50", alt: 'facebook logo'), 'http://www.facebook.com/sharer.php?u='+ request.original_url, :target => :blank  %>

<%= link_to image_tag('google_plus_icon.png', size: "70x70" , alt: 'G+ logo'), 'https://plus.google.com/share?url=' + request.original_url %>
</p>

<p> <%= image_tag @item.image.url(:medium), :class  => "style_image" %> </p>

<div class="description"> <%= @item.description %> </div>

<br>

<p> <strong> Comments </strong> </p>
<%= link_to "Add your comment" , item_path(@item, type: 'comment'),  remote: true %>

<% @item.comments.each do |comment| %>
  <table class="comment_table">  
    <thead>
      <tr>
        <th> <%= comment.user_name %>  </th>
        <% if logged_in? %>
        <td> <%= link_to 'Destroy', "#{@item.id}/comments/#{comment.id}" ,  method: :delete, data: {   confirm: 'Are you sure?' } %> </td>


        <% else %>
        <!-- This is used for decoration, nothing else -->  
        <td> </td>

        <% end %>

      </tr> 
    </thead>

    <tbody>
      <tr> 
        <td> <%= comment.content %> </td>
      </tr>
      <% @replies.each do |reply| %>
        <% if comment.id == reply.source_id  %>
          <tr> 
            <td style="padding-left: 25px; width:50%; word-wrap:break-word"> <strong> <%= reply.user_name %> </strong> </td>
          </tr>          

          <tr> 
            <td style="padding-left: 50px; width: 50%; word-wrap:break-word"> <%= reply.content %> </td>
          </tr>

        <% end %>
      <% end %>
      
      <tr> <td style="padding-left: 25px"> <%= link_to "Reply" , item_path(@item, type: 'reply', :comment_id => comment.id ), remote: true %> </td> </tr>
    </tbody>
  </table>  
<br>  
<% end %>

<div id="task-form"> </div> 
<div id="form_comment"> </div>


<br>
<br>

app/views/items/show.js.erb
var format_type = "<%= j (params[:type]) %>"


$('#task-form').slideUp(350);

if (format_type == "comment") {
  // alert(format_type)
  $('#form_comment').html("<%= j (render :partial => 'sub_form_comment') %>");
} else if (format_type == "reply") {
  // alert(format_type)
  $('#form_comment').html("<%= j (render :partial => 'sub_form_reply') %>");
} 

app/views/layouts/_footer.html.erb
<small>
  <nav>
    <%= link_to "Home",   root_path %>
    <%= link_to "Help",   help_path %>
    <%= link_to "Contact", contact_path %>
  </nav>
</small>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
      <% if logged_in? %>
        <li><%= link_to "Log out", logout_path, method: "delete" %> </li>
      <% else %>
        <li><%= link_to "Log in", login_path %> </li>
      <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>

<%= render 'shared/error_message' %>

<%= yield %>

<%= render 'layouts/footer' %>
<%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/sale_pages/contact.html.erb
<% provide(:title, "Contact") %>
<div>
	<h1> Welcome to our sale webpage </h1>
	<p> Please contact us via : </p>
	<ul>
		<li> Number: +84 - 125 945 6912 </li>
		<li> Email : <a href="mailto:ng.huyminh91@gmail.com"> Minh Nguyen </a>
	</ul>

</div>

app/views/sale_pages/help.html.erb
<% provide(:title, "Help") %>

<p> Pending ..... </p>

app/views/sale_pages/home.html.erb
<% provide(:title, "Home") %>

<div class="center jumbotron">
	<h1> Welcome to our sale webpage </h1> <br>
</div>  

<marquee>
  <% @items.each do |item| %>
    <%= link_to image_tag(item.image.url(:thumb)), item %>
  <% end %>
</marquee>
<br>

<% if logged_in? %>
  <%= link_to "Add your items", new_path, class: "btn btn-lg btn-primary" %>
<% end %>


<table class="item_table">
  <thead>
    <tr>
      <th class="row-name">Name</th>
      <th class="row-description">Description</th>
      <% if logged_in? %>
      <th colspan="3">Option</th>
      <% else %>
      <th class="row-option">Option</th>
      <% end %>

    </tr>
  </thead>

  <tbody>
    <% @items.each do |idx_item| %>
      <tr>
        <td><%= idx_item.name %></td>
        <td><%= idx_item.description %></td>
        <td><%= link_to 'Show', idx_item %></td>
        <% if logged_in? %>
          <td><%= link_to 'Edit', edit_item_path(idx_item) %></td>
          <td><%= link_to 'Destroy', idx_item, method: :delete, data: {   confirm: 'Are you sure?' } %></td>
        <% end %>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/shared/_error_message.html.erb
<% if flash[:error] %>
  <div class="alert alert-danger"> 
    <% flash[:error].each do |error_type| %>
      <li>
        <ul> <%= error_type %> </ul>
      </li>
    <% end %>
  </div>
<% end %>

app/views/shared/_item_error_message.html.erb
<% if @item.errors.any? %>
  <div id="error_explanation">
      <div class="alert alert-danger">
        The form contains <%= pluralize(@item.errors.count, "error") %>.
      </div>
      <ul>
        <% @item.errors.full_messages.each do |msg| %>
          <li> <%= msg %> </li>
        <% end %>
      </ul>
  </div>
<% end %>